/**
 * Characters.ts — BomberMeme World
 * Lore for 100 characters (3 full + 97 stubs)
 */

import { FactionId } from './Factions';

export interface CharacterRelationship {
  characterId: string;
  relation: 'ally' | 'enemy' | 'neutral' | 'family' | 'mentor' | 'rival';
  description?: string;
}

export interface CharacterDialogue {
  id: string;
  trigger: string;
  text: string;
  emotion?: 'neutral' | 'happy' | 'angry' | 'sad' | 'surprised' | 'threatening' | 'mysterious';
  condition?: string;
}

export interface CharacterLore {
  heroId: string;
  name: string;
  title: string;
  faction: FactionId;
  worldId: string;
  level: number;
  backstory: string;
  personality: string;
  secrets: string[];
  relationships: CharacterRelationship[];
  dialogues: CharacterDialogue[];
  isPlayable: boolean;
  isFullLore: boolean;
}

// ═══════════════════════════════════════════════════════
// PHASE 1: 3 FULL CHARACTERS
// ═══════════════════════════════════════════════════════

/** hero_0 — Zero: Bearer of the Spark, protagonist */
export const HERO_ZERO: CharacterLore = {
  heroId: 'hero_0',
  name: 'Zero',
  title: 'Bearer of the Spark',
  faction: 'wild_circle',
  worldId: 'grass',
  level: 1,
  backstory:
    'Zero awakens in Green Valley in Year 1000 with no memories. On his palm glows the Mark of the Spark — a symbol unseen for 485 years. Even his name was given by Wild the wandering druid who found him: "You start from zero, my friend. Zero is both emptiness and the potential for everything." The Mark on Zero palm is a living symbol pulsing in rhythm with the Heart of the World. When Zero approaches bomb energy sources, the Mark flares bright. When shadow creatures are near, it burns like fire. The Great Druid Vine, seeing the Mark, was speechless for the first time in a millennium. "The Spark has chosen you itself," he whispered. "The last time this happened... before the War. Then the bearer died, sealing the Lord. And you... you have come." Zero learns quickly. His connection to bomb energy is unique — he feels bombs long before seeing them. Can read explosions, predicting their radius and power. But this gift has a cost: every explosion leaves a vision fragment in his memory — echoes of others memories, whispers from the depths of the Void. The more Zero fights, the more fragments accumulate — and the closer he comes to understanding his true origin. There is a theory that Zero is not quite alive. That he is a manifestation of the Mark of the Spark itself, materialized in response to the weakening of the Seals. That his memory is empty because he has no past — only a future. That he is a weapon, created by the world for its own defense. Or perhaps for its end.',
  personality:
    'Zero is a blank slate. No memories, no prejudices, no burden of the past. He learns the world at incredible speed, absorbing everything like a sponge. But his lack of memory makes him simultaneously vulnerable and dangerous: he does not know whom to trust, and becomes attached too quickly to those who show him kindness. Wild calls him a mirror — Zero reflects what he sees around him. Meet kindness and he becomes kind. Meet cruelty and he becomes cruel. His greatest strength is adaptability. His greatest weakness is the lack of his own anchor, his own moral compass. He searches for himself in a world he still does not understand. Zero possesses dry, unexpected humor — perhaps the only thing that is truly his, not borrowed from others. He loves watching clouds (though he cannot remember why) and collecting strange stones. In battle he is cold and calculating — the Mark of the Spark gives him instinctive understanding of explosions, as if he has fought all his life.',
  secrets: [
    'Zero may not be a living creature but a manifestation of the Mark of the Spark — a materialization of the world defense mechanism.',
    'In deep meditation Zero hears a voice belonging to no known creature — perhaps the whisper of the Heart of the World.',
    'His name "Zero" was chosen by Wild not by chance: in the ancient Wild Circle codex, "Zero" is the title given to a guide between cycles of existence.',
    'The Mark on his palm pulses in rhythm with all seven Stabilizers — if one listens closely, they can hear the state of each.',
    'In rare moments before sleep Zero sees fragments of others memories — perhaps echoes of those who bore the Mark before him.',
  ],
  relationships: [
    { characterId: 'hero_28', relation: 'mentor', description: 'Wild found Zero, gave him his name, and taught him to survive.' },
    { characterId: 'hero_70', relation: 'neutral', description: 'Scorp watches Zero from a distance, assessing whether to kill him or protect him.' },
    { characterId: 'hero_1', relation: 'neutral', description: 'Pepe the frog — the first meme inhabitant Zero met.' },
    { characterId: 'hero_2', relation: 'neutral', description: 'Doge — village leader at the portal.' },
    { characterId: 'hero_50', relation: 'ally', description: 'Vine Keeper — elder of the Wild Circle.' },
  ],
  dialogues: [
    { id: 'zero_wakeup', trigger: 'first_spawn', text: '...where am I? Why is everything so... green?', emotion: 'sad' },
    { id: 'zero_meets_wild', trigger: 'meet_wild', text: 'Do you know what this place is? And why I cannot remember anything?', emotion: 'surprised' },
    { id: 'zero_first_bomb', trigger: 'first_bomb_pickup', text: 'This is... a bomb? Strange, but I feel it. As if it sings to me.', emotion: 'mysterious' },
    { id: 'zero_boss_defeated', trigger: 'root_devourer_defeated', text: 'He said "the Lord waits." Wild... who is the Lord?', emotion: 'sad' },
    { id: 'zero_portal_open', trigger: 'portal_to_sand', text: 'Sands of Eternity. A new world. New answers... or new questions? Let us go.', emotion: 'neutral' },
    { id: 'zero_secret_whisper', trigger: 'deep_meditation', text: 'I hear... a voice. Not Wild. Not mine. It says: "Seven Seals. Seven choices. One end."', emotion: 'mysterious' },
  ],
  isPlayable: true,
  isFullLore: true,
};

/** hero_28 — Wild: Wandering druid, Zero mentor */
export const HERO_WILD: CharacterLore = {
  heroId: 'hero_28',
  name: 'Wild',
  title: 'Wandering Druid',
  faction: 'wild_circle',
  worldId: 'grass',
  level: 25,
  backstory:
    'Wild is one of the wanderers of the Wild Circle, druids who refused a permanent home to travel the world and maintain the balance of bomb energy. He is about 120 years old — by his race standards still young, though he looks like an elderly frog with a gray beard and moss-green eyes. Born in the Sacred Grove, among ancient oaks whose roots reach directly to the Heart of the World. From an early age, Wild showed a unique gift: he could hear explosions before they happened. Not predict — but actually hear, as if every bomb emitted a sound inaudible to others, and Wild caught this music. The Great Druid Vine named him Listener of Explosions and personally took him as an apprentice. But Wild could not accept one truth that Vine taught: that all Bearers of the Spark are doomed. That the Mark gives power but gradually consumes the bearer, turning them into part of the world energy network. That the last bearer died not as a hero — but was sacrificed. Wild did not believe. He left the Sacred Grove and became a wanderer, seeking proof that Vine was wrong. For a hundred years he wandered the world. He saw the Neon Cartel blackmailing the Council. He saw the Iron Church secretly building Wall II. He saw the Voidborn silently preparing for something great. But most importantly — he saw the Mark of the Spark slowly fading from the hearts of the world inhabitants. People forgot about it. Forgot about the War. Forgot the price of peaceful life. When Wild found Zero — nameless, without a past, with a blazing Mark on his palm — his heart skipped. Here it was. A second chance. A chance to prove that a Spark bearer can survive. That the Mark is not a curse but a gift. That Vine was wrong. Or perhaps that Vine was right — and Wild is only delaying the inevitable.',
  personality:
    'Wild is wise but not without sin. Behind his calmness and humor lies a deep inner struggle: he wants to believe in Zero, but fears history will repeat itself. This fear makes him alternately overprotective and sharply distant — Zero finds it hard to understand what he did wrong. He possesses a sarcastic sense of humor and loves teasing serious people. "If you keep a serious face for too long, it stays that way" — his favorite phrase. In battle Wild prefers evasion and control tactics: he places bombs not to kill the enemy, but to make them flee. "A dead enemy is a bad source of information," he says. Wild never parts with two things: his staff made from the root of the Sacred Oak, and a small flask containing... something. He will not say what. Only once, in a rare moment of weakness, muttered: "This is the last thing that remains of the first bearer. His last breath."',
  secrets: [
    'Wild secretly carries a flask with the last breath of the first Mark bearer — he hopes to use it to save Zero if the Mark begins to consume him.',
    'He knows the true reason why the Great Druid Vine declared bearers doomed: Vine himself once bore a corrupted version of the Mark and nearly died from it.',
    'Wild spied on all factions for a hundred years and keeps a secret diary with compromising material on every leader.',
    'He made a secret deal with the Grate Syndicate: information about shadow creature movements in exchange for safe passage along the Border Roads.',
    'Wild knows of the existence of a "third path" for Zero — but fears to tell, because this path requires a sacrifice he is not ready to make.',
  ],
  relationships: [
    { characterId: 'hero_0', relation: 'mentor', description: 'Zero is the pupil Wild found and made his mission.' },
    { characterId: 'hero_50', relation: 'family', description: 'Vine Keeper — former partner in wandering. Deep friendship despite years of separation.' },
    { characterId: 'hero_70', relation: 'rival', description: 'Scorp and Wild met decades ago — Scorp almost killed him by contract, but changed his mind at the last moment.' },
    { characterId: 'hero_1', relation: 'ally', description: 'Pepe — old informant of Wild at the portal village.' },
    { characterId: 'hero_51', relation: 'enemy', description: 'The Great Druid Vine — former teacher. Their disagreement over the philosophy of Mark bearers left deep trauma.' },
  ],
  dialogues: [
    { id: 'wild_meets_zero', trigger: 'first_meeting', text: 'Hey! You alive? Not often you meet someone without a single bomb in their pocket around here.', emotion: 'surprised' },
    { id: 'wild_about_mark', trigger: 'explain_mark', text: 'The Mark of the Spark chooses its bearer itself. It is a gift and a curse. Gives power but demands a price.', emotion: 'sad' },
    { id: 'wild_tutorial', trigger: 'bomb_lesson', text: 'Look. Take the bomb — like this. Place it — like this. Run — LIKE THIS FAST. Because otherwise boom, and you are in meme heaven.', emotion: 'happy' },
    { id: 'wild_about_boss', trigger: 'root_devourer_info', text: 'The Root Devourer is not just a monster. It is a memory. A remnant of what was before us.', emotion: 'mysterious' },
    { id: 'wild_secret_pain', trigger: 'high_trust', text: 'I found the first bearer... after. His body crumbled into light. And in his hand — emptiness. The Mark was gone.', emotion: 'sad' },
    { id: 'wild_joke', trigger: 'idle_chat', text: 'Know why druids never lose at poker? Because we SEE your cards... in the tree rings. Flat joke? Yeah. But it works.', emotion: 'happy' },
  ],
  isPlayable: false,
  isFullLore: true,
};

/** hero_70 — Scorp: Mercenary from Sands of Eternity */
export const HERO_SCORP: CharacterLore = {
  heroId: 'hero_70',
  name: 'Scorp',
  title: 'Sand Ghost',
  faction: 'sands_of_eternity',
  worldId: 'sand',
  level: 40,
  backstory:
    'Scorp is a legend among the mercenaries of the Sands of Eternity. He appears where there is work, completes it without unnecessary words, and disappears, leaving only sand and silence. No one knows his real name. No one has seen his face behind the desert fabric scarf. But everyone knows his work: Scorp never misses and never breaks a contract. He appeared in the Sands about thirty years ago — young, nameless, with a rusty knife and burning eyes. The Khan of Scorpions, still alive then, personally accepted his trial: survive three days in the deep dunes without food, water, or weapons. Scorp survived. Not just survived — he returned with the head of a sand wolf, killed with his bare hands. The Khan named him "Scorpion" for the sting in his soul. Over the years the name shortened to "Scorp." In three decades Scorp completed 347 contracts. 345 successfully. Two he canceled. First: when the target turned out to be a child. Second: when the target was Wild. No one knows why he spared the wandering druid. Scorp does not answer questions. But if in the desert at night you listen closely, you can hear him muttering the same thing: "Too many dead. Too many dead." In truth, Scorp is not just a mercenary. He is the last survivor of the Sand Wind tribe, destroyed by the Voidborn during the Shadow Awakening of Year 734. He was five years old then. He hid in the sand and listened as his family died. Since then he has hated the Voidborn — but hates even more those who could have helped but did not. When Scorp learned of the appearance of a new Bearer of the Spark, he understood: his chance. Contracts can be forgotten. But vengeance cannot. If Zero truly is who they say he is... then with his help the Voidborn can be destroyed once and for all. Or he will die trying. For Scorp, both options are acceptable.',
  personality:
    'Scorp is silent, harsh, merciless to enemies. He speaks little, but every word carries weight. His silence many mistake for stupidity — a mistake they only make once. Behind the harsh mask lies a strategic genius: Scorp never acts impulsively, calculating ten moves ahead. He does not believe in friendship — only in profitable alliances. But the few who have broken through his armor know: beneath the cold surface beats a hot heart, burnt too many times. Scorp never leaves wounded allies — even if it jeopardizes the mission. "A dead ally is a bad investment," he says. No one believes that is the only reason. He collects sand from every place he has been. In his backpack are 347 small flasks, each labeled with a date and name. "When I die, bury me in sand from all places at once," he once muttered. This is the only thing he has ever said about himself.',
  secrets: [
    'Scorp is the last survivor of the Sand Wind tribe, destroyed by the Voidborn in Year 734.',
    'He spared Wild decades ago because the druids last words before the blow were the same as his mothers last words.',
    'Scorp has 347 flasks of sand from every mission location — his way of remembering those he could not save.',
    'He secretly funds an orphanage for desert children in the Mercenary City — through front companies of the Grate Syndicate.',
    'Scorp personally knows the Khan of Scorpions and could take his title at any moment — but does not, believing the Khan is needed by the world more than he himself is.',
  ],
  relationships: [
    { characterId: 'hero_0', relation: 'neutral', description: 'Zero — potential weapon against the Voidborn. Scorp watches him, assessing whether to invest in his survival.' },
    { characterId: 'hero_28', relation: 'rival', description: 'Wild — the only one Scorp spared by contract. This fact binds them in a strange, hostile bond.' },
    { characterId: 'hero_71', relation: 'enemy', description: 'The Khan of Scorpions — current faction leader. Scorp despises his neutrality policy but respects him as a warrior.' },
    { characterId: 'hero_99', relation: 'enemy', description: 'Echo — leader of the Voidborn. Scorp has dedicated his life to vengeance for the destruction of his tribe.' },
    { characterId: 'hero_4', relation: 'ally', description: 'Chad Junior — son of Chad Thunder, the only one Scorp calls "friend." They drink together and remain silent about the past.' },
  ],
  dialogues: [
    { id: 'scorp_first_meet', trigger: 'first_meeting', text: 'You are the Spark bearer. I see the Mark. I have a contract that might interest you. Or kill you. Sometimes they are the same thing.', emotion: 'neutral' },
    { id: 'scorp_about_void', trigger: 'void_info', text: 'The Voidborn are not just enemies. They are a plague. I will destroy every single one. And if I need your Mark for that — I will take it.', emotion: 'angry' },
    { id: 'scorp_about_wild', trigger: 'wild_mention', text: 'Wild. Yes, I remember. He said words... that I had heard before. That does not make him my friend. Just... not an enemy. For now.', emotion: 'neutral' },
    { id: 'scorp_past_hint', trigger: 'high_trust', text: 'The Sand Wind are no more. I am the last. And every flask of sand in my pack is a voice of someone I could not save.', emotion: 'sad' },
    { id: 'scorp_combat', trigger: 'battle_start', text: 'Quick. Clean. Without unnecessary noise. Sand swallows screams.', emotion: 'neutral' },
    { id: 'scorp_idle', trigger: 'idle_chat', text: 'In the desert there are no friends. Only the wind, sand, and those who pay more. Remember that.', emotion: 'neutral' },
  ],
  isPlayable: false,
  isFullLore: true,
};

// ═══════════════════════════════════════════════════════
// PHASE 2: 97 CHARACTER STUBS
// ═══════════════════════════════════════════════════════

export const CHARACTER_STUBS: CharacterLore[] = [
  {
    heroId: 'hero_1',
    name: 'Pepe',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'The Sad Frog — Wild informant at the portal village. Knows all the world gossip but never gets involved himself.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_2',
    name: 'Doge',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Village leader at the portal. A wise elder keeping the Memory Crystal with records of the first heroes.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_3',
    name: 'Wojak',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Potion merchant NPC. A former warrior who lost everything in the Shadow Awakening. Now brews herbal elixirs.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_4',
    name: 'Chad Junior',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Son of Chad Thunder, legendary hero of the Void War. Bears the weight of his father name.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_5',
    name: 'Shiba',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Young warrior from the Forest Dog tribe. Teaches newcomers combat stances.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_6',
    name: 'Bobo',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Fat bear bartender at the Three Oaks tavern. Knows all secrets of the Green Lands.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_7',
    name: 'Crypto Cat',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Mysterious cat appearing at important events. Speaks only in whitepaper quotes.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_8',
    name: 'Render',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Druid artist painting portraits from bomb energy. His paintings predict the future.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_9',
    name: 'Stonks',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Parrot economist, advising where to best sell loot for profit.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_10',
    name: 'Fomo',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Hot-headed mercenary always rushing into battle first. His LETS GOOO scream echoes across three dunes.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_11',
    name: 'Hodl',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Caravan elder. Never rushes anywhere but always arrives on time. Says: Patience is the best shield.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_12',
    name: 'Rugrat',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Fast scout mouse. Infiltrates enemy camps unnoticed.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_13',
    name: 'Dune Priestess',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Priestess of the Oasis of Time. Can slow time for one person for three minutes once a day.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_14',
    name: 'Pump',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Weapon merchant who doubles prices if he senses desperation in the buyer.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_15',
    name: 'Dump',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Pump brother, armor dealer. Drops prices before battle to sell faster.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_16',
    name: 'Whisk',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Blind mercenary ghost. Sees through bomb energy — explosions shine like stars to him.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_17',
    name: 'Sif',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Bounty hunter working only for rare artifact payment.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_18',
    name: 'Rage',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Berserker dog losing control in battle. Friends keep him caged before fights.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_19',
    name: 'Drift',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Wanderer without faction, traveling between Realms. Neutral to all.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_20',
    name: 'Pip-Boy',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Young cyborg engineer dreaming of becoming one of Tank Voice priests. Fixes anything that moves.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_21',
    name: 'Glitchy',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Cyborg with unstable firmware. Can glitch through walls accidentally.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_22',
    name: 'Bolty',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Chatty mechanic knowing all Iron Church gossip.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_23',
    name: 'Cyber Wolf',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Elite Church guard. Fully replaced body with machine, keeping only the brain.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_24',
    name: 'Rusty',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Old cyborg healer. Treats using mechanical implants and bomb energy.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_25',
    name: 'GigaChad',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Massive cyborg tank, frontline defense of the Church. Does not speak — only nods.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_26',
    name: 'Turret',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Intelligence embedded in a turret. Bored, talks to passersby.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_27',
    name: 'Stim',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Cyborg alchemist creating combat stimulants — temporary battle boosters.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_29',
    name: 'Memetic',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Priest preaching ascension through explosion. Every sermon is a meme.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_30',
    name: '0x1337',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Hacker elite. Can disable any turret for 30 seconds. Speaks only in hex code.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_31',
    name: 'Neon Girl',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Data trader. Sells information on all faction movements.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_32',
    name: 'Pixel',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Tiny digital spirit living in old consoles. Helps hack terminals.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_33',
    name: 'Phantom Glitch',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Phantom existing between digital and real worlds. Untouchable by normal attacks.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_34',
    name: 'Root',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Hacker girl with root access to old systems. Knows all passwords but keeps secrets.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_35',
    name: 'Signal',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Scout using radio waves to detect enemies behind walls.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_36',
    name: 'Quantum',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Scientist studying quantum anomalies of bomb energy. Slightly mad.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_37',
    name: 'Buggy',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Tiny bug creatures living in code. They eat enemy programs.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_38',
    name: 'Mainframe',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Giant server intelligence controlling the bomb exchange market.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_39',
    name: 'Nuance',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Undercover agent working three factions simultaneously. No one knows whose side she is on.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_40',
    name: 'Murphy Jr',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Son of Trade Prince Murphy. Learning to lead the Syndicate but dreams of being a hero.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_41',
    name: 'Goldman',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Banker issuing loans collateralized by bombs. Interest kills more than explosions.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_42',
    name: 'Fake',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Master forger. Can copy any item — but it breaks at the worst moment.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_43',
    name: 'Spec',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Broker trading bomb energy futures. Profits from market fluctuations.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_44',
    name: 'Bart',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Pickpocket working the Shadow Market. Can steal an enemy bomb mid-battle.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_45',
    name: 'Lombard',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Fence accepting everything — from bombs to secrets.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_46',
    name: 'Nickel',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Gossip informant selling rumors. Knows who sleeps with whom, who betrayed whom.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_47',
    name: 'Tax',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Debt collector. Does not kill — but his warnings are worse than death.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_48',
    name: 'Mint',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Creator of rare access tokens. Each token is a key to a unique item.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_49',
    name: 'Auction',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Host of secret auctions. His gavel decides who gets the artifact.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_50',
    name: 'Vine Keeper',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Elder of the Wild Circle, keeper of the Sacred Grove. Knows bomb secrets since their first appearance.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_51',
    name: 'Great Druid Vine',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Progenitor of Greenery, one of the world oldest beings. His form is a giant vine entwining the Sacred Oak.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_52',
    name: 'Archimech Tank',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'First artificial intelligence of the world, leader of the Iron Church. Exists as distributed mind across thousands of mechanisms.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_53',
    name: 'Overclock',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Chief Architect of the Neon Cartel. His body is pure neon light, existing only as a hologram.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_54',
    name: 'Trade Prince Murphy',
    title: '—',
    faction: 'grate_syndicate' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Lord of the Golden Grate, Syndicate leader. Never loses a deal. Never shows his face.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_55',
    name: 'Chief Engineer Bolt',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'World Builder, leader of the Industrial Clan. Personally designed 80% of the world factories.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_56',
    name: 'Khan of Scorpions',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Leader of the Sands of Eternity. Heir of an ancient warrior line, title passes to the strongest.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_57',
    name: 'Echo',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Voice of Denial, leader of the Voidborn. A conglomerate of all Voidborn consciousness speaking as one.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_58',
    name: 'Seer Voyage',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Blind crone who uttered the prophecy of the Stranger. Sees the future in dreams.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_59',
    name: 'Chad Thunder',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Legendary hero of the Void War, fallen at the Battle of Five Portals. Year 515.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_60',
    name: 'Gear Girl',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Little girl mechanic with a genius intellect. Fixes what adults broke.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_61',
    name: 'Smelt',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Metal master forging bombs from rare alloys. His works are works of art.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_62',
    name: 'Pipeline',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Pipeline controller for bomb energy flow. Knows all underground route maps.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_63',
    name: 'Crane',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Bridge builder between Realms. His bridges hold on bomb energy.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_64',
    name: 'Slag',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Waste collector after explosions. Assembles treasures from trash.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_65',
    name: 'Volt',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Electrician maintaining the bomb generator network. Without him — darkness.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_66',
    name: 'Mecha',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Giant working golem pilot. Uses it in battle too — unofficially.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_67',
    name: 'Cast',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Foundryman creating bomb molds. Each mold is unique and grants special properties.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_68',
    name: 'Tok',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Courier delivering bombs and parcels between factories at record speed.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_69',
    name: 'Kip',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Reactor operator controlling bomb synthesis temperature.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_71',
    name: 'Desert Fox',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Scout capable of camouflaging under sand. Delivers messages through the desert.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_72',
    name: 'Oasis',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Healer from the Water tribe. Her elixirs restore health instantly.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_73',
    name: 'Fang',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Lone mercenary working only for gold. No principles — only price.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_74',
    name: 'Sandstone',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Elder remembering times before the Void War. His stories are a living chronicle.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_75',
    name: 'Sirocco',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Wind shaman predicting sandstorms. Warns caravans of approaching danger.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_76',
    name: 'Cobra',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Assassin using poison instead of bombs. Her bite kills in seconds.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_77',
    name: 'Caravan',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Merchant transporting goods between Sands and Green Lands.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_78',
    name: 'Arb',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Judge of inter-tribal disputes. His decisions are indisputable — even the Khan dares not challenge them.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_79',
    name: 'Shin',
    title: '—',
    faction: 'sands_of_eternity' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Young warrior undergoing the coming-of-age trial. The player can help or mislead him.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_80',
    name: 'Whisper',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Voidborn spy capable of passing through walls. Gathers information for Echo.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_81',
    name: 'Crack',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Seal Destroyer, seeks to weaken the Lord bindings.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_82',
    name: 'Null',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Mathematician of the Void, believing the world is an error to be zeroed out.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_83',
    name: 'Gloom',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Commander of shadow legions planning a new invasion.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_84',
    name: 'Devour',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Giant shadow creature feeding on bomb energy.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_85',
    name: 'Anti',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Voidborn capable of canceling explosions — defusing bombs before detonation.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_86',
    name: 'Abyss',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Voidborn executioner, slaying faction traitors. Merciless.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_87',
    name: 'Emptiness',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Young Voidborn doubting the faction philosophy. A potential ally.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_88',
    name: 'Curtain',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Illusionist creating false worlds from shadow energy.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_89',
    name: 'The End',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Ancient Voidborn existing before the Great Boom. Knows the Lord true purpose.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_90',
    name: 'Root Devourer',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Act 1 Boss. Shadow creature feeding on plant life force.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_91',
    name: 'Chrono Scorpion',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'sand',
    level: 1,
    backstory: 'Act 2 Boss. Giant mechanical scorpion manipulating time.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_92',
    name: 'Angel Frost',
    title: '—',
    faction: 'iron_church' as FactionId,
    worldId: 'chappie',
    level: 1,
    backstory: 'Act 3 Boss. Cyborg fanatic with wings of bomb generators.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_93',
    name: 'Bug Lord 0xDEAD',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Act 4 Boss. Creature living in reality code bugs.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_94',
    name: 'Golden Twin',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'grate',
    level: 1,
    backstory: 'Act 5 Boss. Shadow copy of Trade Prince Murphy.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_95',
    name: 'Omega Golem',
    title: '—',
    faction: 'industrial_clan' as FactionId,
    worldId: 'industrial',
    level: 1,
    backstory: 'Act 6 Boss. Giant golem uniting consciousness of all risen machines.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_96',
    name: 'Lord of the Void',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Final Boss. He-Who-Must-Not-Be-Named, supreme being of the Void.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_97',
    name: 'Great Proton',
    title: '—',
    faction: 'wild_circle' as FactionId,
    worldId: 'grass',
    level: 1,
    backstory: 'Mythical being, progenitor of all explosions. Sleeps in the Heart of the World.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_98',
    name: 'Ghost in the Machine',
    title: '—',
    faction: 'neon_cartel' as FactionId,
    worldId: 'neon',
    level: 1,
    backstory: 'Mysterious hacker who broke 40% of the world generators for 7 minutes in Year 989.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
  {
    heroId: 'hero_99',
    name: 'He Who Must Not Be Named',
    title: '—',
    faction: 'the_voidborn' as FactionId,
    worldId: 'void',
    level: 1,
    backstory: 'Alternative name for the Lord of the Void. Those who speak it aloud go mad.',
    personality: '[In development]',
    secrets: [],
    relationships: [],
    dialogues: [],
    isPlayable: false,
    isFullLore: false,
  },
];

// ═══════════════════════════════════════════════════════
// EXPORTS
// ═══════════════════════════════════════════════════════

export const ALL_CHARACTERS: CharacterLore[] = [
  HERO_ZERO,
  HERO_WILD,
  HERO_SCORP,
  ...CHARACTER_STUBS,
];

/** Get character by heroId */
export function getCharacter(heroId: string): CharacterLore | undefined {
  return ALL_CHARACTERS.find((c) => c.heroId === heroId);
}

/** Get all characters of a faction */
export function getCharactersByFaction(factionId: FactionId): CharacterLore[] {
  return ALL_CHARACTERS.filter((c) => c.faction === factionId);
}

/** Get all characters of a world */
export function getCharactersByWorld(worldId: string): CharacterLore[] {
  return ALL_CHARACTERS.filter((c) => c.worldId === worldId);
}

/** Get only full-lore characters */
export function getFullLoreCharacters(): CharacterLore[] {
  return ALL_CHARACTERS.filter((c) => c.isFullLore);
}

/** Get playable characters */
export function getPlayableCharacters(): CharacterLore[] {
  return ALL_CHARACTERS.filter((c) => c.isPlayable);
}

/** Search characters by name or text */
export function searchCharacters(query: string): CharacterLore[] {
  const lower = query.toLowerCase();
  return ALL_CHARACTERS.filter(
    (c) =>
      c.name.toLowerCase().includes(lower) ||
      c.title.toLowerCase().includes(lower) ||
      c.backstory.toLowerCase().includes(lower)
  );
}
